# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.1"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  #
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "salt-dev"

  ## For masterless, mount your salt file root
  config.vm.synced_folder "../salt", "/srv/salt"
  config.vm.synced_folder "../pillar", "/srv/pillar"
  config.vm.synced_folder "../test", "/srv/test"

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.run_highstate = true
    salt.minion_config = "salt-dev-minion"
    salt.verbose = true
  end
end
